import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "../styles/main.scss";

// Import Roboto Mono font (monospace) for code-like appearance
// Using next/font/google for automatic optimization (Critical Mass performance requirement)
const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  display: "swap", // Better performance - shows fallback font while loading
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={robotoMono.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
