import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Import Inter font as specified in project-idea.md
// Using next/font/google for automatic optimization (Critical Mass performance requirement)
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap", // Better performance - shows fallback font while loading
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        {children}
      </body>
    </html>
  );
}
